// <auto-generated />
namespace NotePro.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class firstCodeMigrate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstCodeMigrate));
        
        string IMigrationMetadata.Id
        {
            get { return "202008280143252_firstCodeMigrate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
